// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: allocator.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MakeAllocationRequest is a request to make an allocation.
type MakeAllocationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// size is the size of the allocation.
	Size uint64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// duration is the duration of the allocation.
	Duration      *durationpb.Duration `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeAllocationRequest) Reset() {
	*x = MakeAllocationRequest{}
	mi := &file_allocator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeAllocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAllocationRequest) ProtoMessage() {}

func (x *MakeAllocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_allocator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAllocationRequest.ProtoReflect.Descriptor instead.
func (*MakeAllocationRequest) Descriptor() ([]byte, []int) {
	return file_allocator_proto_rawDescGZIP(), []int{0}
}

func (x *MakeAllocationRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MakeAllocationRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

// MakeAllocationResponse is a response to a request to make an allocation.
type MakeAllocationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// value is a simple value.
	Value         uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeAllocationResponse) Reset() {
	*x = MakeAllocationResponse{}
	mi := &file_allocator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeAllocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAllocationResponse) ProtoMessage() {}

func (x *MakeAllocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_allocator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAllocationResponse.ProtoReflect.Descriptor instead.
func (*MakeAllocationResponse) Descriptor() ([]byte, []int) {
	return file_allocator_proto_rawDescGZIP(), []int{1}
}

func (x *MakeAllocationResponse) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_allocator_proto protoreflect.FileDescriptor

const file_allocator_proto_rawDesc = "" +
	"\n" +
	"\x0fallocator.proto\x12\x06schema\x1a\x1egoogle/protobuf/duration.proto\"b\n" +
	"\x15MakeAllocationRequest\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x125\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bduration\".\n" +
	"\x16MakeAllocationResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value2^\n" +
	"\tAllocator\x12Q\n" +
	"\x0eMakeAllocation\x12\x1d.schema.MakeAllocationRequest\x1a\x1e.schema.MakeAllocationResponse\"\x00BCZAgitlab.stageoffice.ru/UCS-COMMON/memlimiter/test/allocator/schemab\x06proto3"

var (
	file_allocator_proto_rawDescOnce sync.Once
	file_allocator_proto_rawDescData []byte
)

func file_allocator_proto_rawDescGZIP() []byte {
	file_allocator_proto_rawDescOnce.Do(func() {
		file_allocator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_allocator_proto_rawDesc), len(file_allocator_proto_rawDesc)))
	})
	return file_allocator_proto_rawDescData
}

var file_allocator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_allocator_proto_goTypes = []any{
	(*MakeAllocationRequest)(nil),  // 0: schema.MakeAllocationRequest
	(*MakeAllocationResponse)(nil), // 1: schema.MakeAllocationResponse
	(*durationpb.Duration)(nil),    // 2: google.protobuf.Duration
}
var file_allocator_proto_depIdxs = []int32{
	2, // 0: schema.MakeAllocationRequest.duration:type_name -> google.protobuf.Duration
	0, // 1: schema.Allocator.MakeAllocation:input_type -> schema.MakeAllocationRequest
	1, // 2: schema.Allocator.MakeAllocation:output_type -> schema.MakeAllocationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_allocator_proto_init() }
func file_allocator_proto_init() {
	if File_allocator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_allocator_proto_rawDesc), len(file_allocator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_allocator_proto_goTypes,
		DependencyIndexes: file_allocator_proto_depIdxs,
		MessageInfos:      file_allocator_proto_msgTypes,
	}.Build()
	File_allocator_proto = out.File
	file_allocator_proto_goTypes = nil
	file_allocator_proto_depIdxs = nil
}
