name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4
          args: ./...

      - name: Verify dependencies
        run: |
          go mod verify

      - name: Validate module graph
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Build
        run: make build

      - name: SWAP
        run: |
          sudo swapon -s
          export PARTITION=$(sudo swapon -s | tail -n 1 | gawk '{print $1;}')
          sudo swapoff $PARTITION
          sudo swapon -s

      - name: Test
        run: make test
