name: memlimiter

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  MemLimiter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.42.1
          args: -c .golangci.yml
