File: .github/workflows/memlimiter.yml
name: memlimiter

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  MemLimiter:
    runs-on: fedora-latest
    steps:
      - name: Hello World!
        run: echo "HW!"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: make build

      - name: Test
        run: make test